(eval-when (eval load compile)
           (define (make-ld-path)
             (let ((ldp (getenv "LD_LIBRARY_PATH")))
               (if ldp (string-append ldp ":" (getcwd)) (getcwd))))
           (setenv "LD_LIBRARY_PATH" (make-ld-path))
           (load "xmp-wrapset.scm"))
(use-modules (libxmp))
(xmp_init #nil)
(define e (xmp_new_empty #nil))
(define xf (xmp_files_open_new "/home/kei/Downloads/memoization2011.pdf" 'XMP_OPEN_NOOPTION))
(define xmp (xmp_files_get_new_xmp xf))
(define xs (xmp_string_new #nil))
(define result (xmp_serialize xmp xs 0 0))
(define s (xmp_string_cstr xs))
(display result)
(display s)
(newline)
(xmp_terminate #nil)
